name: build and deploy static site to S3
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ms

env:
  AWS_REGION : "ap-northeast-1"
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_DEV }}:role/github-actions-s3-deploy-role-ms-web
          role-session-name: PlanSession
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
      - name: Cache NodeJS
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Build And Export
        run: npm run build
      - name: Deploy
        run:
          aws s3 sync --region ${{ env.AWS_REGION }} ./out s3://wakabaseisei-ms-web --delete
